### PR TITLE
Better Handling of zero median values in Kernel Width

### LINKED ISSUE #158: `"InvalidParameterError when running DAS algorithm with rbf_kernel in dodiscover package"`.
## Checklist

- [x] I have verified that the issue exists against the `main` branch.
- [x] I have read the relevant section in the [contribution guide](https://github.com/py-why/dodiscover/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/py-why/dodiscover/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/py-why/dodiscover/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/py-why/dodiscover/blob/main/CHANGELOG.md) and the [commit log](https://github.com/py-why/dodiscover/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

When running the DAS algorithm I encounter the following error:

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/path/to/your/project/examples/DAS_github_issue.py", line 14, in <module>
    das.learn_graph(data, context)
  File "/path/to/your/project/dodiscover/toporder/_base.py", line 705, in learn_graph
    A_dense, order = self._top_order(X)
  File "/path/to/your/project/dodiscover/toporder/score.py", line 107, in _top_order
    X = self._find_leaf_iteration(stein, X, active_nodes, order)
  File "/path/to/your/project/dodiscover/toporder/score.py", line 168, in _find_leaf_iteration
    H_diag = stein_instance.hessian_diagonal(X, self.eta_G, self.eta_H)
  File "/path/to/your/project/dodiscover/toporder/_base.py", line 160, in hessian_diagonal
    K = self._evaluate_kernel(X, s)
  File "/path/to/your/project/dodiscover/toporder/_base.py", line 221, in _evaluate_kernel
    K = rbf_kernel(X, gamma=1 / (2 * s**2)) / s
  File "/path/to/python/environment/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 203, in wrapper
    validate_parameter_constraints(
  File "/path/to/python/environment/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'gamma' parameter of rbf_kernel must be a float in the range [0.0, inf) or None. Got inf instead.
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Ubuntu 20.04.6 LTS

Python version: 3.10.14

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
absl-py==2.1.0
aioboto3==13.0.1
aiobotocore==2.13.0
aiofiles==23.2.1
aiohttp==3.9.5
aioitertools==0.11.0
aiosignal==1.3.1
annotated-types==0.7.0
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1717693030552/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1692818318753/work
argon2-cffi-bindings @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi-bindings_1695386546427/work
arrow @ file:///home/conda/feedstock_root/build_artifacts/arrow_1696128962909/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
async-lru @ file:///home/conda/feedstock_root/build_artifacts/async-lru_1690563019058/work
async-timeout==4.0.3
attrs==23.2.0
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1702422572539/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1705564648255/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1696630167146/work
bnlearn @ git+https://github.com/erdogant/bnlearn@5e465c234f1a557a652cc5db246282dd5f7750cf
boto3==1.34.106
botocore==1.34.106
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1695989787169/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
CausalDisco==0.2.0
-e git+https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git@d0bc352534dcbfac19a84a1bb05f33fe311378d2#egg=cdt
certifi==2024.6.2
cffi==1.16.0
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1698833585322/work
chex==0.1.86
click==8.1.7
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
contourpy==1.2.1
cycler==0.12.1
datazets==0.1.9
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1707444420542/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
deeplake==3.9.9
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
df2onehot==1.0.7
dill==0.3.8
dodiscover==0.0.0.dev0
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
equinox==0.11.4
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1704921103267/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
fastjsonschema==2.19.1
filelock==3.13.1
fonttools==4.52.1
fqdn @ file:///home/conda/feedstock_root/build_artifacts/fqdn_1638810296540/work/dist
frozenlist==1.4.1
fsspec==2024.2.0
funcsigs==1.0.2
gadjid==0.1.0
gcastle==1.0.3
GPUtil==1.4.0
graphviz==0.20.3
h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1664132893548/work
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1634280454336/work
hpack==4.0.0
httpcore @ file:///home/conda/feedstock_root/build_artifacts/httpcore_1711596990900/work
httpx @ file:///home/conda/feedstock_root/build_artifacts/httpx_1708530890843/work
humbug==0.3.2
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1619110129307/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1713279365350/work
igraph==0.11.5
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1710971335535/work
importlib_resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1711040877059/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1708996548741/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1715263367085/work
ipywidgets==8.1.3
ismember==1.0.5
isoduration @ file:///home/conda/feedstock_root/build_artifacts/isoduration_1638811571363/work/dist
jax==0.4.28
jax-cuda12-pjrt==0.4.28
jax-cuda12-plugin==0.4.28
jaxlib==0.4.28+cuda12.cudnn89
jaxopt==0.8.3
jaxtyping==0.2.28
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2==3.1.3
jmespath==1.0.1
joblib==1.4.2
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1712986206667/work
jsonpointer==2.4
jsonschema==4.22.0
jsonschema-specifications @ file:///tmp/tmpkv1z7p57/src
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1710805637316/work
jupyter-lsp @ file:///home/conda/feedstock_root/build_artifacts/jupyter-lsp-meta_1712707420468/work/jupyter-lsp
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1716472197302/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1710257277185/work
jupyter_server==2.14.1
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1710262634903/work
jupyterlab==4.2.1
jupyterlab_pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1707149102966/work
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
kiwisolver==1.4.5
libdeeplake==0.0.129
lz4==4.3.3
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1706899921127/work
matplotlib==3.9.0
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1698947099619/work
ml-dtypes==0.4.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1710317608672/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1718135430380/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1712238998817/work
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
networkx==3.2.1
notebook==7.2.0
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1707957777232/work
numpy==1.26.4
nvidia-cublas-cu12==12.5.2.13
nvidia-cuda-cupti-cu12==12.5.39
nvidia-cuda-nvcc-cu12==12.5.40
nvidia-cuda-nvrtc-cu12==12.5.40
nvidia-cuda-runtime-cu12==12.5.39
nvidia-cudnn-cu12==8.9.7.29
nvidia-cufft-cu12==11.2.3.18
nvidia-cusolver-cu12==11.6.2.40
nvidia-cusparse-cu12==12.4.1.24
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.5.40
opt-einsum==3.3.0
optax==0.2.2
overrides @ file:///home/conda/feedstock_root/build_artifacts/overrides_1706394519472/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1710075952259/work
pandas==2.2.2
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
pathos==0.3.2
patsy==0.5.6
-e git+https://github.com/liukidar/pcax.git@6c4c89204a06c02a9d29130c85b414d245d6e0be#egg=pcax
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
pgmpy==0.1.25
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pillow==10.2.0
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1694617248815/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1715777629804/work
pox==0.3.4
ppft==1.7.6.8
progressbar2==4.4.2
prometheus_client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1707932675456/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1702399386289/work
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1705722392846/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1711811537435/work
pydantic==2.7.4
pydantic_core==2.18.4
pygam==0.9.1
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
PyJWT==2.8.0
pyparsing==3.1.2
pypickle==1.1.0
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
python-louvain==0.16
python-utils==3.8.2
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1706886791323/work
pywhy-graphs==0.1.0
PyYAML==6.0.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1715024398995/work
qtconsole==5.5.2
QtPy==2.4.1
referencing @ file:///home/conda/feedstock_root/build_artifacts/referencing_1714619483868/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1717057054362/work
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rpds-py==0.18.1
s3transfer==0.10.1
scikit-learn==1.5.0
scipy==1.11.4
seaborn==0.13.2
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1712584999685/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
skrebate==0.62
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1708952932303/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1693929250441/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
statsmodels==0.14.2
sympy==1.12
tabulate==0.9.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1710262609923/work
texttable==1.7.0
threadpoolctl==3.5.0
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1713974937325/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
toolz==0.12.1
torch==2.3.0+cpu
torchaudio==2.3.0+cpu
torchvision==0.18.0+cpu
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1717722796999/work
tqdm==4.66.4
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
tueplots==0.0.15
typeguard==2.13.3
types-python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/types-python-dateutil_1710589910274/work
typing-utils @ file:///home/conda/feedstock_root/build_artifacts/typing_utils_1622899189314/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1712329955671/work
tzdata==2024.1
uri-template @ file:///home/conda/feedstock_root/build_artifacts/uri-template_1688655812972/work/dist
urllib3==2.2.1
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
webcolors==1.13
webencodings @ file:///home/conda/feedstock_root/build_artifacts/webencodings_1694681268211/work
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1713923384721/work
widgetsnbextension==4.0.11
wrapt==1.16.0
yarl==1.9.4
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work
zstandard==0.23.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
import bnlearn as bn
import numpy as np
from pywhy_graphs.viz import draw
from dodiscover import make_context
from dodiscover.toporder import DAS

# Load example dataset
data = bn.import_example(data='asia')

context = make_context().variables(data=data).build()

# learn the graph structure with DAS algorithm
das = DAS()
das.learn_graph(data, context)
das_graph = das.graph_
draw(das_graph, direction='TB')
```

</p>
</details>

### PR DESCRIPTION
**Pull request by nparent1**
Fixes #158 

Changes proposed in this pull request:
Modifies the kernel_width() method to take the median only of non-zero pairwise distances, similar to how pywhy-stats does [here](https://github.com/py-why/pywhy-stats/blob/fcd82f88a9d9fdd0587129f9b5c5e89a317838f0/pywhy_stats/kernels.py#L73). 

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/dodiscover/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/dodiscover/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.
- [ ] I have added a changelog entry succintly describing the change in this PR in the [whats_new](https://github.com/py-why/dodiscover/blob/main/docs/whats_new/) relevant version document.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by nparent1** [comment]
To give more details as to why this fixes the particular issue reported in #158 - In score.py 's _top_order method, X is iteratively reduced down to just a single column [here](https://github.com/nparent1/dodiscover/blob/ade4e48f0ecfe8ac26f3ddf69e8eead095e4b2d4/dodiscover/toporder/score.py#L107). In the case of the reporter, the dataset consisted of ones and zeros, and so it isn't unreasonable that the median pairwise distance of such a dataset (especially when the diagonals are counted as well) would be zero.

And so this method proceeds to call the [_estimate_var function](https://github.com/nparent1/dodiscover/blob/ade4e48f0ecfe8ac26f3ddf69e8eead095e4b2d4/dodiscover/toporder/score.py#L110), on this single column of data, which downstream will get the kernel width (which could be zero) and call [evaluate_kernel](https://github.com/nparent1/dodiscover/blob/8f6fb2a30d3eaecce37a39455804c49a64af1319/dodiscover/toporder/_base.py#L167), which gives the error the reporter is reporting.

**Comment by nparent1** [comment]
I don't have permission to add the 'No Changelog Needed' label - but I think that is appropriate for this PR, if the reviewer could add!

**Comment by adam2392** [comment]
I'm wondering what's the effect of biasing towards 1 in the limit. Cuz the median can theoretically go from 0.1, 0.01, 1e-8, …, and then all of a sudden to 1. 

Is this fix supported, or documented anywhere?

**Comment by adam2392** [comment]
@francescomontagna wdyt about this fix to make the kernel width usable when there are many 0's in the dataset resulting in a kernel width of "0"?

**Comment by nparent1** [comment]
Regarding the choice to bias towards 1. I can't find documentation or references in causal-learn, but I do see pywhy-stats does this [here](https://github.com/py-why/pywhy-stats/blob/fcd82f88a9d9fdd0587129f9b5c5e89a317838f0/pywhy_stats/kernels.py#L76). My motivation for this was to prevent throwing an error when all of the pairwise distances are zero, because the median of the nonzero elements does not exist.

In this situation (all pairwise distances are zero, so all the data points are identical), I assumed the kernel width doesnt really matter because the kernel will always come out to zero regardless of the width. I can definitely revert commit https://github.com/py-why/dodiscover/pull/160/commits/c7229ee82228bfb2bd3c5945f1d307260dbf96f2 if you think its better to throw an error though @adam2392 


causal-learn does seem to filter out zeros when taking the median though ([here](https://github.com/py-why/causal-learn/blob/7bd7c68dae4e452c1005bb21f89beb71c7f25b01/causallearn/search/FCMBased/lingam/hsic.py#L43) and [here](https://github.com/py-why/causal-learn/blob/7bd7c68dae4e452c1005bb21f89beb71c7f25b01/causallearn/utils/KCI/GaussianKernel.py#L33) for example).

**Comment by nparent1** [comment]
Done!

**Comment by nparent1** [comment]
Any remaining concerns @adam2392?

**Review by adam2392 — APPROVED** [review]
LGTM if CIs are green

**Comment by adam2392** [comment]
CI seems unrelated. LGTM!

**Comment by adam2392** [comment]
Thanks @nparent1 !

**Comment by francescomontagna** [comment]
> @francescomontagna wdyt about this fix to make the kernel width usable when there are many 0's in the dataset resulting in a kernel width of "0"?

Hi @adam2392 and @nparent1 . Thanks for taking care of this. I actually had to discuss this with people who wrote me about issues in the kernel width estimation, so I think a fix is due. I see adam's concern of biasing towards one, yet, as this solution seems common according to nick's references, I am fine with it. Thanks!

**Pull request merged**
